export { default as filterPanel } from './filterPanel.vue'
export { default as carList } from './carList.vue'
export { default as detailBase } from './detailBase.vue'
export { default as detailPlan } from './detailPlan.vue'
export { default as detailConfig } from './detailConfig.vue'
