// MTZ-规则清单
export const ruleTableTitle = [//决策资料规则清单暂用
    { 
        props: 'ruleNo',
        name: 'Year CW',
        // key: 'Year CW',
        // overlap:true,
        // overlapbottom:"Rule No.",
        minWidth:80
    },
    {
        props: 'materialGroup',
        name: 'Nomination No.',
        // key: 'Nomination No.',
        // overlap:true,
        // overlapbottom:"MTZ group",
        minWidth:103
    },
    { 
        props: 'carline', 
        name: 'Rule No.', 
        // key: 'Rule No.',
        // overlap:true,
        // overlapbottom:"Carline",
        minWidth:60,
    },
    {
        props: 'supplierId',
        name: 'MTZ Materiral',
        // key: 'GONGYINGSHANG',
        overlap:true,
        overlapbottom:"Group",
        minWidth:110,
    },
    {
        props: 'materialCode',
        name: 'Carline',
        // key: 'Carline',
        // overlap:true,
        // overlapbottom:"Material Code",
        minWidth:80,
    },
    {
        props: 'materialName',
        name: 'Supplier',
        // key: 'Supplier',
        // overlap:true,
        // overlapbottom:"Material Division",
        minWidth:100,
    },
    { 
        props: 'price', 
        name: 'Material', 
        // key: 'Material',
        // overlap:true,
        // overlapbottom:"Base price",
        minWidth:70,
    },
    {
        props: 'priceMeasureUnit',
        name: 'Maaterial',
        // key: 'Maaterial',
        overlap:true,
        overlapbottom:"Code",
        minWidth:115,
    },
    { 
        props: 'tcCurrence', 
        name: 'Price', 
        // key: 'Price',
        // overlap:true,
        // overlapbottom:"Currency",
        minWidth:70,
    },
    { 
        props: 'tcExchangeRate', 
        name: 'Price', 
        // key: 'Price',
        overlap:true,
        overlapbottom:"Unit",
        minWidth:105,
    },
    {
        props: 'source',
        name: 'Currency',
        // key: 'Currency',
        // overlap:true,
        // overlapbottom:"Market",
        minWidth:95,
    },
    {
        props: 'compensationPeriod',
        name: 'Exchange',
        // key: 'Exchange',
        overlap:true,
        overlapbottom:"Rate",
        minWidth:80,
    },
    { 
        props: 'startDate', 
        name: 'Price', 
        // key: 'Price',
        overlap:true,
        overlapbottom:"Market",
        minWidth:90,
    },
    { 
        props: 'endDate', 
        name: 'Period', 
        // key: 'Period',
        // overlap:true,
        // overlapbottom:"Valid To",
        minWidth:90,
    },
    { 
        props: 'endDate', 
        name: 'Valid From', 
        // key: 'Valid From',
        // overlap:true,
        // overlapbottom:"Valid To",
        minWidth:90,
    },
    { 
        props: 'endDate', 
        name: 'Valid To', 
        // key: 'Valid To',
        // overlap:true,
        // overlapbottom:"Valid To",
        minWidth:90,
    },
]

// MTZ-零件清单
export const partTableTitle = [
    { 
        props: 'ruleNo',
        name: 'Year CW',
        // key: 'Year CW',
        // overlap:true,
        // overlapbottom:"Rule No.",
        minWidth:80
    },
    {
        props: 'materialGroup',
        name: 'Nomination No.',
        // key: 'Nomination No.',
        // overlap:true,
        // overlapbottom:"MTZ group",
        minWidth:103
    },
    { 
        props: 'carline', 
        name: 'Part No.', 
        // key: 'Rule No.',
        // overlap:true,
        // overlapbottom:"Carline",
        minWidth:60,
    },
    {
      props: 'materialCode',
      name: 'Part Name',
    //   key: 'YUANCAILIAOBIANHAO',
    //   overlap:true,
    //   overlapbottom:"Material Code",
      minWidth: 80,
    },
    { 
        props: 'materialName', 
        name: 'Supplier',
        // key: 'YUANCAILIAO',
        // overlap:true,
        // overlapbottom:"Material",
        minWidth: 60,
    },
    { 
        props: 'supplierId', 
        name: 'Material', 
        // key: 'GONGYINGSHANG',
        // overlap:true,
        // overlapbottom:"Supplier",
        minWidth: 60,
    },
    {
        props: 'price', 
        name: 'Material', 
        // key: 'JIJIA',
        overlap:true,
        overlapbottom:"Code",
         minWidth: 70,
    },
    {
        props: 'priceMeasureUnit',
        name: 'Usage',
        // key: 'JIJIAJILIANGDANWEI',
        // overlap:true,
        // overlapbottom:"Base price Unit",
        minWidth: 80,
    },
    { 
        props: 'priceUnit', 
        name: 'Usage', 
        // key: 'MEI',
        overlap:true,
        overlapbottom:"Unit",
        minWidth: 50,
    },
    {
        props: 'partUnit',
        name: 'Currency',
        // key: 'LINGJIANSHULIANGDANWEI',
        // overlap:true,
        // overlapbottom:"Part Unit",
        minWidth: 80,
    },
    { 
        props: 'dosage', 
        name: 'Exchange', 
        // key: 'YONGLIANG',
        overlap:true,
        overlapbottom:"Rate",
        minWidth: 60,
    },
    {
        props: 'dosageMeasureUnit',
        name: 'Price',
        // key: 'YONGLIANGJILIANGDANWEI',
        overlap:true,
        overlapbottom:"Market",
        minWidth: 80,
    },
    {
        props: 'priceSource',
        name: 'Period',
        // key: 'SHICHANGJIALAIYUAN',
        // overlap:true,
        // overlapbottom:"Market",
        minWidth: 70,
    },
    { 
        props: 'startDate', 
        name: 'Valid From',
        // key: 'YOUXIAOQIQI',
        // overlap:true,
        // overlapbottom:"Valid From",
        minWidth: 75,
    },
    { 
        props: 'endDate', 
        name: 'Valid To', 
        // key: 'YOUXIAOQIZHI',
        // overlap:true,
        // overlapbottom:"Valid To",
        minWidth: 75,
    },
]